deploy apollo stack to the swarm
apolloconfig/apollo pull request #3569
Opened 2021-02-24 03:24 UTC by aibeb

## What's the purpose of this PR

deploy apollo stack to the swarm

## Which issue(s) this PR fixes:

deploy apollo stack to the swarm

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [ ] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [ ] Run `mvn clean test` to make sure this pull request doesn't break anything.

2021-02-25 00:17 UTC, nobodyiam commented on scripts/apollo-on-swarm/README.md
> +  --env APOLLO.ADMIN-SERVICE.URL=http://apollo-adminservice:8090 \
env 的命名规范一般都是用下划线的，这里统一也改一下吧
```suggestion
  --env APOLLO_CONFIG_SERVICE_URL=http://${APOLLO.CONFIG-SERVICE.URL}:8080 \
  --env APOLLO_ADMIN_SERVICE_URL=http://apollo-adminservice:8090 \
```

2021-02-25 02:04 UTC, aibeb commented on scripts/apollo-on-swarm/README.md
> +  --env APOLLO.ADMIN-SERVICE.URL=http://apollo-adminservice:8090 \
这里没有采用下划线是因为apollo-configservbice/src/main/config/application-github.properties中没有接受下划线环境变量的配置, 如果需要支持下划线需要pr去修改application-github.properties 这个我可以附带到我到pr中

2021-02-26 00:01 UTC, nobodyiam commented on scripts/apollo-on-swarm/README.md
> +  --env APOLLO.ADMIN-SERVICE.URL=http://apollo-adminservice:8090 \
下划线是支持的，spring 会自动适配不同格式的配置的，`apollo.config-service.url`和`APOLLO_CONFIG_SERVICE_URL`等价

2021-02-27 08:33 UTC, nobodyiam requested changes

2021-02-27 08:33 UTC, nobodyiam commented on scripts/apollo-on-swarm/README.md
> +docker stack deploy -c ./docker-compose.yaml apollo
mac 电脑上运行该命令报错

```bash
invalid interpolation format for services.apollo-mysql.volumes.[]: "$(pwd)/../scripts/docker-quick-start/sql:/docker-entrypoint-initdb.d". You may need to escape any $ with another $.
```

2021-02-27 08:33 UTC, nobodyiam commented on scripts/apollo-on-swarm/README.md
> +docker stack deploy -c ./docker-compose.yaml apollo
注释掉 apollo-mysql 相关内容后，看上去也是环境变量没拿到

```bash
Error response from daemon: rpc error: code = InvalidArgument desc = ContainerSpec: "apolloconfig/apollo-configservice:" is not a valid repository/tag
```

2021-06-06 07:24 UTC, JaredTan95 commented
as https://github.com/ctripcorp/apollo/pull/3747 merged, please update [changs log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md). :-)

2021-06-13 05:46 UTC, nobodyiam commented
@aibeb any update on this?

2021-12-20 11:11 UTC, closed without merging