Document Update: Add an example to load config in shell
apolloconfig/apollo pull request #3853
Opened 2021-07-27 08:06 UTC by lff0305

Document Update：Example for using shell script with curl to fetch config with Security Key enabled.

No code updated.

## What's the purpose of this PR

Document update: using curl to fetch config with Security Key enabled.

## Which issue(s) this PR fixes:
Fixes # NA.

## Brief changelog

4606648 Add shell script to fetch from config server.

2021-07-27 08:10 UTC, lff0305 commented
I have read the CLA Document and I hereby sign the CLA

2021-07-27 11:34 UTC, Anilople commented
Please Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

2021-07-27 11:38 UTC, Anilople requested changes

2021-07-27 11:38 UTC, Anilople commented on docs/zh/usage/other-language-client-user-guide.md
> +```
```suggestion
```bash
```

2021-07-27 11:38 UTC, Anilople commented on docs/zh/usage/other-language-client-user-guide.md
> +appid="app1"                                                  // 修改需要读取的appid
comment in bash is start with `#`.

How about change to 
```suggestion
# 需要读取的appid
appid="app1"
```

2021-08-29 11:30 UTC, nobodyiam commented
as 1.9.0 was released, please update against the latest CHANGES.md, thanks!

2021-09-10 12:53 UTC, nobodyiam commented on CHANGES.md
> +* [extend DataChange_CreatedBy, DataChange_LastModifiedBy from 32 to 64.](https://github.com/ctripcorp/apollo/pull/3552)
It seems these are items in 1.9.0 release note...

2021-10-03 01:13 UTC, nobodyiam commented on CHANGES.md
> +* [Document: Load configurations from shell scriopt](https://github.com/apolloconfig/apollo/pull/3853)
```suggestion
* [Document: Load configurations from shell script](https://github.com/apolloconfig/apollo/pull/3853)
```

2021-10-05 13:43 UTC, Anilople requested changes

2021-10-05 13:43 UTC, Anilople commented on docs/zh/usage/shell-user-guide.md
> +### 使用Shell Script读取Apollo的配置
rename to `shell-sdk-user-guide.md`?

2021-10-05 13:43 UTC, Anilople commented on docs/zh/usage/other-language-client-user-guide.md
> +参见[shell 脚本例子](./shell-user-guide.md)
删除这里的内容，通过_sidebar.md添加shell客户端的目录，会不会更好一些

例如添加一行**shell客户端使用指南**到 https://github.com/apolloconfig/apollo/blob/master/docs/zh/_sidebar.md
```markdown
- 使用文档
  - [Apollo使用指南](zh/usage/apollo-user-guide.md)
  - [Java客户端使用指南](zh/usage/java-sdk-user-guide.md)
  - [Shell客户端使用指南](zh/usage/shell-sdk-user-guide.md)
  - [.Net客户端使用指南](zh/usage/dotnet-sdk-user-guide.md)
  - [Go、Python、NodeJS、PHP等客户端使用指南](zh/usage/third-party-sdks-user-guide.md)
  - [其它语言客户端接入指南](zh/usage/other-language-client-user-guide.md)
```

这样在 左边侧边栏 目录就可以看到 Shell客户端使用指南 了

2021-12-20 11:11 UTC, closed without merging