A PR for PropertiesTest.java
apolloconfig/apollo pull request #4113
Opened 2021-11-23 14:57 UTC by youyulan

## What's the purpose of this PR

I write a test file for \apollo-core\src\main\java\com\ctrip\framework\apollo\core\utils\PropertiesUtils.java

## Which issue(s) this PR fixes:
Fixes #3874

## Brief changelog

write two test method for the two function in PropertiesUtils.java seperately.

Follow this checklist to help us incorporate your contribution quickly and easily:

- [ ] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [ ] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [ ] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

2021-11-23 15:22 UTC, youyulan commented
I have read the CLA Document and I hereby sign the CLA

2021-11-24 14:20 UTC, Anilople requested changes
Thank you for your time to participate in open source contributions.

Welcome!

2021-11-24 14:20 UTC, Anilople commented on apollo-core/src/test/java/com/ctrip/framework/apollo/core/utils/PropertiesUtilTest.java
> +    public void TestProperties() throws IOException {
```suggestion
    public void testToString() throws IOException {
```
`Test` => `test`

2021-11-24 14:20 UTC, Anilople commented on apollo-core/src/test/java/com/ctrip/framework/apollo/core/utils/PropertiesUtilTest.java
> +        assertTrue("".equals(PropertiesUtil.toString(new Properties())));
Use assertEqual or assertEquals instead of assertTrue

2021-11-24 14:20 UTC, Anilople commented on apollo-core/src/test/java/com/ctrip/framework/apollo/core/utils/PropertiesUtilTest.java
> +        assertTrue("a=aaa\r\n".equals(PropertiesUtil.toString(properties))
User System.lineSeperator instead of hard code `\r\n` `\n`

2021-11-24 14:20 UTC, Anilople commented on apollo-core/src/test/java/com/ctrip/framework/apollo/core/utils/PropertiesUtilTest.java
> +        StringBuffer sb=new StringBuffer("#aaaaa\nbbb");
String.join(System.lineSepeartor, "#aaaaa“, "bbb"); ?

2021-11-24 14:20 UTC, Anilople commented on apollo-core/src/test/java/com/ctrip/framework/apollo/core/utils/PropertiesUtilTest.java
> +    public void TestFilterComment(){
```suggestion
    public void testFilterPropertiesComment(){
```
Keep the method name's convention of test case.

2021-11-24 14:20 UTC, Anilople commented on apollo-core/src/test/java/com/ctrip/framework/apollo/core/utils/PropertiesUtilTest.java
> +        PropertiesUtil.filterPropertiesComment(sb);
You can add more test case to cover all conditional branchs

https://github.com/apolloconfig/apollo/blob/9e19898c6dc3e14fa1424a827ecc60519e21bd16/apollo-core/src/main/java/com/ctrip/framework/apollo/core/utils/PropertiesUtil.java#L46-L57

2021-11-26 07:03 UTC, zouyx commented on apollo-core/src/test/java/com/ctrip/framework/apollo/core/utils/PropertiesUtilTest.java
> + * @author Wu Mingkan(Dalian University of Technology)
Should delete author in community project.

2021-11-27 02:00 UTC, Anilople approved these changes
LGTM

2021-11-27 02:01 UTC, merged