modify .github\workflows\cla.yml
apolloconfig/apollo pull request #4150
Opened 2021-12-12 13:59 UTC by Fool-coder

## What's the purpose of this PR

Change pathname

## Which issue(s) this PR fixes:

File https://github.com/apolloconfig/apollo/blob/master/.github/workflows/cla.yml#L37 also need change too.
Just change ctripcorp/ to apolloconfig/ simply.

2021-12-12 14:18 UTC, Anilople requested changes

2021-12-12 14:18 UTC, Anilople commented on README.md
> +- User/Password: apollo/admin
This file should not modify.

2021-12-12 15:01 UTC, Fool-coder commented
I have read the CLA Document and I hereby sign the CLA

2021-12-13 13:17 UTC, Anilople approved these changes
LGTM

2021-12-13 13:19 UTC, merged