fix bug: associated namespace parse text incorrect
apolloconfig/apollo pull request #4219
Opened 2022-01-26 02:24 UTC by darcydai

…icNamespace.isPropertiesFormat`  not set

## What's the purpose of this PR

1.  associated namespace parse text incorrect because of field `publicNamespace.isPropertiesFormat`  not set

## Which issue(s) this PR fixes:
Fixes #
As below
![image](https://user-images.githubusercontent.com/20854418/151093268-77ec4e52-91dc-4951-be16-5b87ff18bb0f.png)

![image](https://user-images.githubusercontent.com/20854418/151093248-bda80bfa-2bec-47d6-8e1f-792884adb5cd.png)

## Brief changelog

associated namespace display in text incorrect

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [x] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [ ] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

2022-01-26 03:54 UTC, nobodyiam requested changes
Thanks for the fix! 
Please also update the CHANGES.md and sign the CLA.

2022-01-26 03:54 UTC, nobodyiam commented on apollo-portal/src/main/resources/static/scripts/directive/namespace-panel-directive.js
> +                            publicNamespace.isPropertiesFormat = publicNamespace.format == 'properties'
I suggest appending a `;` to be consistent with other codes.
```suggestion
                            publicNamespace.isPropertiesFormat = publicNamespace.format == 'properties';
```

2022-01-26 06:03 UTC, darcydai commented
I have read the CLA Document and I hereby sign the CLA

2022-01-26 06:38 UTC, darcydai commented
I have read the CLA Document and I hereby sign the CLA

2022-01-27 09:34 UTC, nobodyiam approved these changes
LGTM

2022-01-27 09:34 UTC, merged