fix issue #4252 fail to boot after enable oidc with keycloak 15.x.x
apolloconfig/apollo pull request #4253
Opened 2022-03-06 11:00 UTC by liaolunhui

## What's the purpose of this PR

fix issue #4252 fail to boot after enable oidc with keycloak 15.x.x

## Which issue(s) this PR fixes:
Fixes #4252 

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [ ] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [ ] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [ ] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

2022-03-06 11:08 UTC, liaolunhui commented
I have read the CLA Document and I hereby sign the CLA

2022-03-07 01:01 UTC, nobodyiam commented
@vdisk-group Would you please help to review this pr?

2022-03-07 02:07 UTC, vdisk-group requested changes
please move the dependency above the test dependencies and extract the version to the properties like this
```
	<properties>
... other properties
		<!-- Dependencies Version -->
		<oauth2-oidc-sdk.version>9.27</oauth2-oidc-sdk.version>
	</properties>
	<dependencies>
... other dependencies
		<dependency>
			<groupId>com.nimbusds</groupId>
			<artifactId>oauth2-oidc-sdk</artifactId>
			<version>${oauth2-oidc-sdk.version}</version>
			<scope>runtime</scope>
		</dependency>
		<!-- test -->
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>test</scope>
		</dependency>
... test dependencies
	</dependencies>
```

2022-04-06 00:22 UTC, vdisk-group commented
fixed by #4295

2022-04-06 00:22 UTC, closed without merging