Fix test update branch gray rules with update once
apolloconfig/apollo pull request #4597
Opened 2022-10-04 21:23 UTC by ZhewenFu

## What's the purpose of this PR

Fix test `testUpdateBranchGrayRulesWithUpdateOnce`

## Which issue(s) this PR fixes:
Fixes the issue that causes flaky tests. The current test may lead to inconsistent ordering of stringified JSON objects and the test may fail sometimes. To fix the test and make it consistent, I select all the elements in the list and see whether the release history contains those elements. In this case, the ordering of the elements doesn't matter and won't cause failure.

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [ ] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [ ] Run `mvn clean test` to make sure this pull request doesn't break anything.
- [ ] Update the [`CHANGES` log](https://github.com/ctripcorp/apollo/blob/master/CHANGES.md).

2022-10-05 12:35 UTC, mghio requested changes
BTW, please use the [apollo code style](https://github.com/apolloconfig/apollo/tree/master/apollo-buildtools/style) for format the codes.

2022-10-05 12:35 UTC, mghio commented on apollo-biz/src/test/java/com/ctrip/framework/apollo/biz/service/NamespaceBranchServiceTest.java
> +  public boolean containRule(String context, String rule){
How about use `private`?

2022-10-05 12:35 UTC, mghio commented on apollo-biz/src/test/java/com/ctrip/framework/apollo/biz/service/NamespaceBranchServiceTest.java
> +    String[] rules = rule.substring(2,rule.length()-2).split(",");
I think use [GrayReleaseRuleItemTransformer#batchTransformFromJSON](https://github.com/apolloconfig/apollo/blob/301d66dcc28b2d698eefed3ecc9aa3273afb9ddf/apollo-common/src/main/java/com/ctrip/framework/apollo/common/utils/GrayReleaseRuleItemTransformer.java#L35) parse  rules might be better. What do you think?

2022-10-10 01:26 UTC, ZhewenFu commented
I have read the CLA Document and I hereby sign the CLA

2022-10-10 01:27 UTC, ZhewenFu commented
>

2022-10-10 01:27 UTC, closed without merging